title:             O:CONNECT
email:             oconnect@gmail.com
description:       Connect the World
author:            Kyuhwan Shim
baseurl:           ""
url:               "https://oconnectx.github.io"

# Social Profiles

instagram_username:    
facebook_username:  OConnect-100615271652569

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

kramdown:
  math_engine:       mathjax
#  math_engine_opts:
#    preview:         true
#    preview_as_code: true
